### PR TITLE
Issue #5 fix:Make assets local

### PR DESCRIPTION
**Pull request by niteshpk**
I have downloaded all the images in the `images/png/` folder also created the folder called `fonts`. Please review the PR and provide your inputs. 
@mehulmpt Please check and update it.

### CODE REVIEW

**Comment by niteshpk** [comment]
@mehulmpt - Any updates on this PR?

**Comment by mehulmpt** [comment]
Hi niteshpk,
Great work! Give me a few days time, I'll review this PR soon!

**Comment by niteshpk** [comment]
@mehulmpt  - 
Okay. Take your time, But make sure to review this PR. And let me know if there are any changes needed. Thanks.

**Comment by mehulmpt** [comment]
Nice work.

**Comment by niteshpk** [comment]
Thanks... Will love to work on some other works too.. 

@mehulmpt  - Happy to help.

**Pull request merged**
